Document: mingw-w64-pdcurses
Title: Debian mingw-w64-pdcurses Manual
Author: <insert document author here>
Abstract: This manual describes what mingw-w64-pdcurses is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mingw-w64-pdcurses/mingw-w64-pdcurses.sgml.gz

Format: postscript
Files: /usr/share/doc/mingw-w64-pdcurses/mingw-w64-pdcurses.ps.gz

Format: text
Files: /usr/share/doc/mingw-w64-pdcurses/mingw-w64-pdcurses.text.gz

Format: HTML
Index: /usr/share/doc/mingw-w64-pdcurses/html/index.html
Files: /usr/share/doc/mingw-w64-pdcurses/html/*.html
